name: veil_wallet
description: Veil light wallet made with flutter
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.21+27

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter  
  flutter_localizations:
    sdk: flutter
  intl: any
  veil_light_plugin:
    path: ./submodules/veil_light_plugin
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size
  extended_text: ^14.1.0
  file_picker: ^8.1.3
  flutter_secure_storage: ^9.2.2
  local_auth: ^2.3.0
  url_launcher: ^6.3.1
  provider: ^6.1.2
  pretty_qr_code: ^3.3.0
  screenshot: ^3.0.0
  share_plus: ^10.1.0
  qr_code_scanner: ^1.0.1
  http: ^1.2.2
  convert: ^3.1.2
  pointycastle: ^3.9.1
  path_provider: ^2.1.4
  package_info_plus: ^8.1.0
  shared_preferences: ^2.3.2
  l10n_esperanto: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/logo.png
    - assets/images/logo_full.png
    - assets/images/logo_full_light.png
    - assets/images/pattern.png
    - assets/res/legal.txt

flutter_native_splash:
  android_disable_fullscreen: true