name: veil_wallet
description: Veil light wallet made with flutter
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.10+16

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter  
  flutter_localizations:
    sdk: flutter
  intl: any
  veil_light_plugin:
    path: ./submodules/veil_light_plugin
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size
  extended_text: ^13.0.0
  file_picker: ^6.2.0
  flutter_secure_storage: ^9.0.0
  local_auth: ^2.1.8
  url_launcher: ^6.2.5
  provider: ^6.1.2
  pretty_qr_code: ^3.3.0
  screenshot: ^2.1.0
  share_plus: ^7.2.2
  qr_code_scanner: ^1.0.1
  http: ^1.1.2
  convert: ^3.1.1
  pointycastle: ^3.7.4
  path_provider: ^2.1.2
  package_info_plus: ^5.0.1
  shared_preferences: ^2.2.2
  l10n_esperanto: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/logo.png
    - assets/images/logo_full.png
    - assets/images/logo_full_light.png
    - assets/images/pattern.png
    - assets/res/legal.txt

flutter_native_splash:
  android_disable_fullscreen: true